import type { OutstandingJob } from "./tracker"

export function buildUnpolledShellJobMessage(jobs: readonly OutstandingJob[]): string {
  const lines = jobs.map((job) => `- \`${job.jobId}\` — \`${job.command}\``)
  const plural = jobs.length === 1 ? "job is" : "jobs are"

  return [
    `<unpolled-background-shell-jobs>`,
    `You are ending your turn with ${jobs.length} detached \`ctx_shell\` ${plural} still outstanding:`,
    ...lines,
    ``,
    `\`ctx_shell(run_in_background=true)\` **does not notify** on completion — unlike`,
    `\`task(run_in_background=true)\`, no \`<system-reminder>\` will ever arrive for it. If you`,
    `end the turn expecting one, the work stalls until a human intervenes.`,
    ``,
    `Resolve every job listed above before yielding. Pick ONE of:`,
    ``,
    `**A. Wait for it — \`background_action="wait"\`, which both waits AND clears.**`,
    `This is the cheapest option and usually the right one:`,
    ...jobs.map((job) => `\`ctx_shell(background_action="wait", job_id="${job.jobId}")\``),
    ``,
    `It blocks server-side until the job is terminal or \`wait_timeout_ms\` elapses (default`,
    `45s, max 50s). A terminal reply — \`completed, exit 0\`, \`failed, exit 1\`, or that the id`,
    `is already gone — **deregisters the job**, so no follow-up call is needed. A reply of`,
    `\`wait timed out … still running\` means exactly that: call \`wait\` again. Each check-in`,
    `costs one call per ~45s, so a 5-minute job is ~6 calls rather than ~30.`,
    ``,
    `Firing \`background_action="status"\` over and over is the failure mode this replaces: it`,
    `burns a dozen turns, floods the context, and reports nothing \`wait\` would not have`,
    `returned. Use \`status\` only to peek at a running job without blocking.`,
    ``,
    `If you must key on a marker in the job's own log instead, a bounded loop works:`,
    ``,
    "```bash",
    `for i in $(seq 1 50); do`,
    `  grep -qE "BUILD (SUCCESSFUL|FAILED)|<your done marker>" /tmp/job.log 2>/dev/null && break`,
    `  sleep 2`,
    `done`,
    "```",
    ``,
    `(The "never sleep-poll" guidance is about a single blind \`sleep 300\`, which wastes the`,
    `full wait even when the job finished in 5s. A loop that breaks on completion is correct.)`,
    ``,
    `**But that loop alone does NOT clear the job.** Only a \`ctx_shell\` call naming the job`,
    `id deregisters it — reading a marker file, a log, or a verdict file is invisible here,`,
    `so this warning will fire again on work you already finished. After a marker loop,`,
    `close every job with one terminal call:`,
    ...jobs.map((job) => `\`ctx_shell(background_action="status", job_id="${job.jobId}")\``),
    ``,
    `**B. You no longer need it — cancel explicitly:**`,
    ...jobs.map((job) => `\`ctx_shell(background_action="cancel", job_id="${job.jobId}")\``),
    ``,
    `**C. You already consumed its result by other means.** A job whose output you read from`,
    `a file is still registered — that is the most common reason a job you know finished is`,
    `listed above. Same fix: one \`background_action="status"\` or \`"wait"\` call clears it,`,
    `whether it reports a terminal status or that the id is already gone; \`cancel\` (B)`,
    `always clears it.`,
    ``,
    `Next time, prefer not to detach at all: \`ctx_shell\` runs in the FOREGROUND up to ~110s,`,
    `which covers most builds and test runs. Detaching is for work that genuinely exceeds`,
    `that — and if the work is delegable, \`task(run_in_background=true)\` notifies, so it can`,
    `be awaited by simply ending the turn.`,
    `</unpolled-background-shell-jobs>`,
  ].join("\n")
}
