import type { OutstandingJob } from "./tracker"

export function buildUnpolledShellJobMessage(jobs: readonly OutstandingJob[]): string {
  const lines = jobs.map((job) => `- \`${job.jobId}\` — \`${job.command}\``)
  const plural = jobs.length === 1 ? "job is" : "jobs are"

  return [
    `<unpolled-background-shell-jobs>`,
    `You are ending your turn with ${jobs.length} detached \`ctx_shell\` ${plural} still outstanding:`,
    ...lines,
    ``,
    `\`ctx_shell(run_in_background=true)\` **does not notify** on completion — unlike`,
    `\`task(run_in_background=true)\`, no \`<system-reminder>\` will ever arrive for it. If you`,
    `end the turn expecting one, the work stalls until a human intervenes.`,
    ``,
    `Resolve every job listed above before yielding. Pick ONE of:`,
    ``,
    `**A. Wait for it — bounded loop, then ONE terminal \`status\` call.**`,
    `Wait in a single shell call that exits as soon as the job lands:`,
    ``,
    "```bash",
    `for i in $(seq 1 50); do`,
    `  grep -qE "BUILD (SUCCESSFUL|FAILED)|<your done marker>" /tmp/job.log 2>/dev/null && break`,
    `  sleep 2`,
    `done`,
    "```",
    ``,
    `That is one call and it returns the moment the work finishes. Firing`,
    `\`background_action="status"\` over and over is the failure mode this replaces: it burns a`,
    `dozen turns, floods the context, and reports nothing the loop would not have caught.`,
    `(The "never sleep-poll" guidance is about a single blind \`sleep 300\`, which wastes the`,
    `full wait even when the job finished in 5s. A loop that breaks on completion is correct.)`,
    ``,
    `**The loop alone does NOT clear the job.** Only a \`ctx_shell\` call naming the job id`,
    `deregisters it — reading a marker file, a log, or a verdict file is invisible here, so`,
    `this warning will fire again on work you already finished. Close every waited-on job`,
    `with one terminal call:`,
    ...jobs.map((job) => `\`ctx_shell(background_action="status", job_id="${job.jobId}")\``),
    ``,
    `**B. You no longer need it — cancel explicitly:**`,
    ...jobs.map((job) => `\`ctx_shell(background_action="cancel", job_id="${job.jobId}")\``),
    ``,
    `**C. You already consumed its result by other means.** A job whose output you read from`,
    `a file is still registered — that is the most common reason a job you know finished is`,
    `listed above. Same fix: one \`background_action="status"\` call (A) clears it on a`,
    `terminal status or \`not found\`; \`cancel\` (B) always clears it.`,
    ``,
    `Next time, prefer not to detach at all: \`ctx_shell\` runs in the FOREGROUND up to ~110s,`,
    `which covers most builds and test runs. Detaching is for work that genuinely exceeds`,
    `that — and if the work is delegable, \`task(run_in_background=true)\` notifies, so it can`,
    `be awaited by simply ending the turn.`,
    `</unpolled-background-shell-jobs>`,
  ].join("\n")
}
