#!/usr/bin/env bash
# Proves BackgroundManager adopts orphaned child after opencode serve restart.
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$SCRIPT_DIR/lib/common.sh"
SELF_TEST=0; EVIDENCE_DIR=""
while [ $# -gt 0 ]; do case "$1" in --self-test) SELF_TEST=1;; --evidence-dir) EVIDENCE_DIR="${2:?--evidence-dir needs DIR}"; shift;; -h|--help) echo "Usage: $0 [--self-test] --evidence-dir DIR"; exit 0;; *) echo "unknown option: $1" >&2; exit 2;; esac; shift; done
[ -n "$EVIDENCE_DIR" ] || EVIDENCE_DIR="${TMPDIR:-/tmp}/resume-adopt-restart-$(date +%s)"; mkdir -p "$EVIDENCE_DIR"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"; HOST_DB="$(opencode db path)"; BEFORE="$(sqlite3 "$HOST_DB" 'SELECT count(*) FROM session')"; printf '%s\n' "$BEFORE" > "$EVIDENCE_DIR/45-host-session-count-before.txt"
FAKE_PID=""; SERVER_PID=""; SERVER_PORT=""; FAKE_PORT=""
cleanup() { for pid in "$SERVER_PID" "$FAKE_PID"; do [ -n "$pid" ] && kill "$pid" 2>/dev/null || true; done; for pid in "$SERVER_PID" "$FAKE_PID"; do [ -n "$pid" ] && wait "$pid" 2>/dev/null || true; done; { printf 'server_pid=%s alive=' "$SERVER_PID"; kill -0 "$SERVER_PID" 2>/dev/null && printf yes || printf no; printf '\nfake_pid=%s alive=' "$FAKE_PID"; kill -0 "$FAKE_PID" 2>/dev/null && printf yes || printf no; printf '\n'; } > "$EVIDENCE_DIR/56-cleanup-receipt.txt"; }
trap cleanup EXIT
oqa_mk_isolated_xdg; OQA_PROJ="$(node -e 'const {realpathSync}=require("fs");console.log(realpathSync(process.argv[1]))' "$OQA_PROJ")"
FAKE_LOG="$EVIDENCE_DIR/46-fake-openai.log"; FAKE_PORT="$(oqa_free_port)"; FAKE_LLM_LOG="$FAKE_LOG" FAKE_OPENAI_PORT="$FAKE_PORT" RESUME_ADOPT_CHILD_ID_FILE="$EVIDENCE_DIR/.child-id" bun run --bun "$SCRIPT_DIR/lib/fake-openai-server.mjs" > "$EVIDENCE_DIR/46-fake-openai.stdout" 2>&1 & FAKE_PID=$!
for _ in $(seq 1 50); do curl -sf "http://127.0.0.1:$FAKE_PORT/health" >/dev/null && break; sleep .2; done; curl -sf "http://127.0.0.1:$FAKE_PORT/health" >/dev/null || { echo 'fake LLM unavailable' >&2; exit 1; }
mkdir -p "$XDG_CONFIG_HOME/opencode"
cat > "$XDG_CONFIG_HOME/opencode/opencode.jsonc" <<JSONC
{"plugin":["file://${REPO_ROOT}/dist/index.js"],"model":"openai/gpt-fake","provider":{"openai":{"options":{"apiKey":"fake-key","baseURL":"http://127.0.0.1:${FAKE_PORT}/v1","timeout":30000},"models":{"gpt-fake":{"tool_call":true,"limit":{"context":200000,"output":8192}}}}},"permission":{"task":"allow","background_output":"allow"}}
JSONC
printf '%s\n' "$XDG_DATA_HOME" > "$EVIDENCE_DIR/47-isolated-xdg-root.txt"
start_server() { SERVER_PORT="$(oqa_free_port)"; OPENCODE_SERVER_PASSWORD="probe-pass" opencode serve --hostname 127.0.0.1 --port "$SERVER_PORT" > "$EVIDENCE_DIR/48-opencode-serve-${1}.log" 2>&1 & SERVER_PID=$!; for _ in $(seq 1 100); do curl -sf -u opencode:probe-pass "http://127.0.0.1:$SERVER_PORT/global/health" > "$EVIDENCE_DIR/48-health-${1}.json" && return; sleep .2; done; return 1; }
enc_dir() { python3 -c 'import urllib.parse,sys;print(urllib.parse.quote(sys.argv[1],safe=""))' "$OQA_PROJ"; }
new_session() { curl -sf -u opencode:probe-pass -X POST "http://127.0.0.1:$SERVER_PORT/session?directory=$(enc_dir)" -H content-type:application/json -d '{"title":"resume adopt restart"}' | jq -r .id; }
prompt() { curl -sf -u opencode:probe-pass -X POST "http://127.0.0.1:$SERVER_PORT/session/$1/prompt_async?directory=$(enc_dir)" -H content-type:application/json -d "{\"parts\":[{\"type\":\"text\",\"text\":\"$2\"}]}" >/dev/null; }
wait_idle() { for _ in $(seq 1 100); do curl -sf -u opencode:probe-pass "http://127.0.0.1:$SERVER_PORT/session/status" | grep -q "$1" || return; sleep .2; done; return 1; }
DB="$XDG_DATA_HOME/opencode/opencode.db"; start_server first; PARENT="$(new_session)"; prompt "$PARENT" 'SPLIT_CHILD_TASK: restart-happy'
for _ in $(seq 1 100); do CHILD="$(sqlite3 "$DB" "SELECT s.id FROM session s JOIN message m ON m.session_id=s.id JOIN part p ON p.message_id=m.id WHERE json_extract(p.data,'$.text') LIKE '%SPLIT_CHILD_TASK: reply exactly DONE%' ORDER BY s.time_created DESC LIMIT 1")"; [ -n "$CHILD" ] && break; sleep .2; done
printf '%s\n' "$CHILD" > "$EVIDENCE_DIR/49-child-id.txt"; printf '%s\n' "$CHILD" > "$EVIDENCE_DIR/.child-id"; [[ "$CHILD" =~ ^ses_[A-Za-z0-9]+$ ]] || exit 1; sqlite3 "$DB" "SELECT id FROM session WHERE id='$CHILD'" | grep -Fx "$CHILD" > "$EVIDENCE_DIR/50-child-row.txt"; wait_idle "$CHILD" || true; PRE="$(sqlite3 "$DB" "SELECT count(*) FROM message WHERE session_id='$CHILD'")"; printf '%s\n' "$PRE" > "$EVIDENCE_DIR/51-pre-restart-message-count.txt"; [ "$PRE" -gt 0 ] || exit 1
kill "$SERVER_PID"; wait "$SERVER_PID" 2>/dev/null || true; kill -0 "$SERVER_PID" 2>/dev/null && exit 1; printf 'server-one-killed=%s\n' "$SERVER_PID" > "$EVIDENCE_DIR/52-server-killed.txt"; SERVER_PID=""; start_server second; sqlite3 "$DB" "SELECT id FROM session WHERE id='$CHILD'" | grep -Fx "$CHILD" > "$EVIDENCE_DIR/53-child-survived-restart.txt"; RESUMER="$(new_session)"; prompt "$RESUMER" "SPLIT_RESUME_ADOPT: $CHILD"; sleep 3; POST="$(sqlite3 "$DB" "SELECT count(*) FROM message WHERE session_id='$CHILD'")"; sqlite3 "$DB" "SELECT session_id, message_id, substr(data,1,300) FROM part WHERE data LIKE '%RESUME_ADOPT_PROBE_CONTINUATION%'" > "$EVIDENCE_DIR/55-happy-marker.txt"; grep -Fq "$CHILD" "$EVIDENCE_DIR/55-happy-marker.txt" || { echo "marker missing from real child transcript" >&2; exit 1; }; printf 'pre=%s post=%s\n' "$PRE" "$POST" > "$EVIDENCE_DIR/54-happy-counts.txt"; HAPPY=FAIL; [ "$POST" -gt "$PRE" ] && grep -Fq 'RESUME_ADOPT_PROBE_CONTINUATION' "$EVIDENCE_DIR/55-happy-marker.txt" && HAPPY=PASS
prompt "$RESUMER" "SPLIT_ACTIVE_CONTROL: $CHILD"; sleep 1; REFUSAL=NOT-REACHED; prompt "$RESUMER" 'SPLIT_ABSENT_CONTROL: ses_doesnotexist'; sleep 1; ABSENT=NOT-REACHED; printf 'HAPPY=%s (pre=%s post=%s)\nREFUSAL=%s\nABSENT=%s\n' "$HAPPY" "$PRE" "$POST" "$REFUSAL" "$ABSENT" > "$EVIDENCE_DIR/57-scenarios.txt"; AFTER="$(sqlite3 "$HOST_DB" 'SELECT count(*) FROM session')"; printf '%s\n' "$AFTER" > "$EVIDENCE_DIR/58-host-session-count-after.txt"; [ "$BEFORE" = "$AFTER" ] || exit 1; [ "$SELF_TEST" -eq 0 ] || [ "$HAPPY" = PASS ]
